#!/usr/bin/env python


IZZI_STATUS_MESSAGE_ID = 0x63

IZZI_STATUS_MSG_ID_INDEX = 0
IZZI_STATUS_MSG_OUTDOR_AIR_TEMP_INDEX = 1
IZZI_STATUS_MSG_EXHAUST_AIR_TEMP_INDEX = 2
IZZI_STATUS_MSG_SUPPLY_AIR_TEMP_INDEX = 3
IZZI_STATUS_MSG_EXTRACT_AIR_TEMP_INDEX = 4
IZZI_STATUS_MSG_COVER_STATE_INDEX = 5
IZZI_STATUS_MSG_BYPASS_STATE_INDEX = 8


IZZI_STATUS_MSG_BYPASS_STATE_CLOSED = 0
IZZI_STATUS_MSG_BYPASS_STATE_OPEN = 1

IZZY_STATUS_MSG_COVER_STATE_OPEN = 5
IZZY_STATUS_MSG_COVER_STATE_CLOSED = 0

IZZI_COMMAND_MESSAGE_ID = 0x64

IZZI_CMD_MSG_ID_INDEX = 0
IZZI_CMD_MSG_BYPASS_TEMP_INDEX = 8
IZZI_CMD_MSG_BYPASS_MODE_INDEX = 9
IZZI_CMD_MSG_SUPPLY_FAN_SPEED_INDEX = 10
IZZI_CMD_MSG_EXTRACT_FAN_SPEED_INDEX = 11
IZZI_CMD_MSG_UNIT_STATE_INDEX = 12

IZZY_CMD_BYPASS_MODE_AUTO = 0
IZZY_CMD_BYPASS_MODE_OPEN = 1
IZZY_CMD_BYPASS_MODE_CLOSED = 2

IZZY_CMD_UNIT_STATE_ON = 0
IZZY_CMD_UNIT_STATE_OFF = 1

IZZY_SENSOR_VENT_MODE_NONE = 0
IZZY_SENSOR_VENT_MODE_FIREPLACE = 1
IZZY_SENSOR_VENT_MODE_OPEN_WINDOW = 2


IZZY_SENSOR_FAN_EXTRACT_SPEED_ID = 0x01
IZZY_SENSOR_FAN_SUPPLY_SPEED_ID = 0x02
IZZY_SENSOR_TEMPERATURE_SUPPLY_ID = 0x03
IZZY_SENSOR_TEMPERATURE_EXTRACT_ID = 0x04
IZZY_SENSOR_TEMPERATURE_EXHAUST_ID = 0x05
IZZY_SENSOR_TEMPERATURE_OUTDOOR_ID = 0x06
IZZY_SENSOR_BYPASS_STATE_ID = 0x07
IZZY_SENSOR_FAN_MODE_ID = 0x08
IZZY_SENSOR_UNIT_STATE_ID = 0x09
IZZY_SENSOR_BYPASS_TEMP_ID = 0x0A
IZZY_SENSOR_BYPASS_MODE_ID = 0x0B
IZZY_SENSOR_VENT_MODE_ID = 0x0C
IZZY_SENSOR_COVER_STATE_ID = 0x0D
IZZY_SENSOR_EFFICIENCY_ID = 0x0E
